export const CONTACTS_REQUEST = 'CONTACTS_REQUEST';
export const CONTACTS_SUCCESS = 'CONTACTS_SUCCESS';
export const CONTACTS_FAILURE = 'CONTACTS_FAILURE';

export const CONTACT_INFO_SHOW = 'CONTACT_INFO_SHOW';
export const CONTACT_INFO_CLOSE = 'CONTACT_INFO_CLOSE';